name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake
        uses: lukka/get-cmake@v3

      - name: Build project
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Run tests
        run: |
          ./build/test_runner
