name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ lcov

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests and export JUnit
      run: |
       mkdir -p test-results
       ./build/test_runner --reporter junit --out test-restults/results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results/results.xml

    - name: Publish Test Report
      uses: dorny/test-reporter@v1
      with:
        name: Catch2 Tests
        path: test-resuts/results.xml
        reporter: junit